table dim_productos
	lineageTag: 62596671-fd85-4ddc-af4e-6c52b39eabff

	column cod_producto
		dataType: string
		lineageTag: 73641035-0be6-499a-b7c4-069746a61091
		summarizeBy: none
		sourceColumn: cod_producto

		annotation SummarizationSetBy = Automatic

	column grupo_product
		dataType: string
		lineageTag: f7ffcfad-2a8b-46b1-955f-86ebaa4b77bc
		summarizeBy: none
		sourceColumn: grupo_product

		annotation SummarizationSetBy = Automatic

	column desc_producto
		dataType: string
		lineageTag: c403376e-2f88-4575-978b-23405f9cde4e
		summarizeBy: none
		sourceColumn: desc_producto

		annotation SummarizationSetBy = Automatic

	column tamanio_pieza
		dataType: double
		lineageTag: eb378181-9bae-4f1e-8d90-277cc0669038
		summarizeBy: sum
		sourceColumn: tamanio_pieza

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column peso_pieza
		dataType: double
		lineageTag: 6f976f34-0b81-4148-99bd-ff05a1384c61
		summarizeBy: sum
		sourceColumn: peso_pieza

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition dim_productos = m
		mode: import
		queryGroup: dimensiones
		source =
				let
				    Origen = Pdf.Tables(AzureStorage.BlobContents("https://hernanalmacen.blob.core.windows.net/csv-data/dataset_productos_powerquery.pdf"), [Implementation="1.3"]),
				    Table001 = Origen{[Id="Table001"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(Table001,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}}),
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Tipo cambiado", [PromoteAllScalars=true]),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Código", type text}, {"Producto", type text}, {"Descripción del producto", type text}, {"Tamaño de la pieza", type text}, {"Peso de la pieza", type text}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado1",{{"Código", "cod_producto"}, {"Producto", "grupo_product"}, {"Descripción del producto", "desc_producto"}, {"Tamaño de la pieza", "tamanio_pieza"}, {"Peso de la pieza", "peso_pieza"}}),
				    #"Texto extraído antes del delimitador" = Table.TransformColumns(#"Columnas con nombre cambiado", {{"tamanio_pieza", each Text.BeforeDelimiter(_, " "), type text}}),
				    #"Texto extraído antes del delimitador1" = Table.TransformColumns(#"Texto extraído antes del delimitador", {{"peso_pieza", each Text.BeforeDelimiter(_, " "), type text}}),
				    #"Tipo cambiado con configuración regional" = Table.TransformColumnTypes(#"Texto extraído antes del delimitador1", {{"tamanio_pieza", type number}}, "en-US"),
				    #"Tipo cambiado con configuración regional1" = Table.TransformColumnTypes(#"Tipo cambiado con configuración regional", {{"peso_pieza", type number}}, "en-US"),
				    #"Texto extraído después del delimitador" = Table.TransformColumns(#"Tipo cambiado con configuración regional1", {{"desc_producto", each Text.AfterDelimiter(_, "-"), type text}}),
				    #"Texto recortado" = Table.TransformColumns(#"Texto extraído después del delimitador",{{"desc_producto", Text.Trim, type text}})
				in
				    #"Texto recortado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

