table 'Table001 (Page 1-2)'
	lineageTag: 62596671-fd85-4ddc-af4e-6c52b39eabff

	column Column1
		dataType: string
		lineageTag: 4653e8b6-0971-4915-acec-9a2b15081e75
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 8cb87b24-094d-4aac-b9d6-961d09f01cdc
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: de90c3cc-bf89-45fb-a5b0-c1be284559f3
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: 8d95dde4-81e9-410c-af72-d2be43e3c5d7
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: 632af817-c72b-4bb8-bd12-8d2820aee019
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	partition 'Table001 (Page 1-2)' = m
		mode: import
		source =
				let
				    Origen = Pdf.Tables(AzureStorage.BlobContents("https://hernanalmacen.blob.core.windows.net/csv-data/dataset_productos_powerquery.pdf"), [Implementation="1.3"]),
				    Table001 = Origen{[Id="Table001"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(Table001,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

